check if image exist before deploy preprod and prod

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -72,6 +72,13 @@ deploy_preprod:
   environment: preprod
   image: alpine/ansible:2.16.1
   script:
+    - echo $CI_JOB_TOKEN | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
+    - |
+      if ! docker pull "$api_docker_image"; then
+        echo "Docker image $api_docker_image does not exist, aborting deployment."
+        exit 1
+      fi
+
     - mkdir /root/.ssh
     - cat "$SSH_KEY" > /root/.ssh/id_rsa
     - cat "$KNOWN_HOSTS" > /root/.ssh/known_hosts
@@ -81,8 +88,6 @@ deploy_preprod:
   rules:
     - if: '$CI_COMMIT_TAG'
       when: manual
-  # needs:
-  #   - build_api
   tags:
     - docker
 
@@ -91,6 +96,13 @@ deploy_prod:
   stage: deploy
   image: alpine/ansible:2.16.1
   script:
+    - echo $CI_JOB_TOKEN | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
+    - |
+      if ! docker pull "$api_docker_image"; then
+        echo "Docker image $api_docker_image does not exist, aborting deployment."
+        exit 1
+      fi
+
     - mkdir /root/.ssh
     - cat "$SSH_KEY" > /root/.ssh/id_rsa
     - cat "$KNOWN_HOSTS" > /root/.ssh/known_hosts
@@ -100,8 +112,7 @@ deploy_prod:
   rules:
     - if: '$CI_COMMIT_TAG'
       when: manual
-  # needs:
-  #   - build_api
+  needs:
+    - deploy_preprod
   tags:
     - docker
-#
